version: '3'

services:
  spc-notify:
    build: spc-notify
    restart: unless-stopped
    environment:
      - AMQP_HOST=rabbit
      - PORT=3000
    ports:
      - 3000:3000
    volumes:
      - ./spc-notify:/usr/src/app
    networks:
      - spc-app-network
    depends_on:
      - rabbit

  rabbit:
    image: rabbitmq
    container_name: spc-rabbit
    volumes:
      - spc_rabbitmq_data:/data
    networks:
      - spc-app-network

networks:
  spc-app-network:
    driver: bridge

volumes:
  spc_rabbitmq_data:
